
discord:
  # See https://javacord.org/wiki/getting-started/creating-a-bot-account.html
  # For how to create a bot account on Discord and get your bot's token
  token: XXXXXXXXX
  server: 
    ### name of your Discord server
    name: 
    channel: wps-delivery

testing: true
